# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import full_node_pb2 as full__node__pb2


class FullNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.push_node_info = channel.unary_unary(
                '/full_node.FullNode/push_node_info',
                request_serializer=full__node__pb2.NodeInfo.SerializeToString,
                response_deserializer=full__node__pb2.NodeInfo.FromString,
                )
        self.push_challenge = channel.unary_unary(
                '/full_node.FullNode/push_challenge',
                request_serializer=full__node__pb2.Challenge.SerializeToString,
                response_deserializer=full__node__pb2.Challenge.FromString,
                )


class FullNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def push_node_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def push_challenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FullNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'push_node_info': grpc.unary_unary_rpc_method_handler(
                    servicer.push_node_info,
                    request_deserializer=full__node__pb2.NodeInfo.FromString,
                    response_serializer=full__node__pb2.NodeInfo.SerializeToString,
            ),
            'push_challenge': grpc.unary_unary_rpc_method_handler(
                    servicer.push_challenge,
                    request_deserializer=full__node__pb2.Challenge.FromString,
                    response_serializer=full__node__pb2.Challenge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'full_node.FullNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FullNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def push_node_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/full_node.FullNode/push_node_info',
            full__node__pb2.NodeInfo.SerializeToString,
            full__node__pb2.NodeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def push_challenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/full_node.FullNode/push_challenge',
            full__node__pb2.Challenge.SerializeToString,
            full__node__pb2.Challenge.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
